import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="#hello">
        <h1 id="hello">Hello</h1>
      </Link>
      <Link href="#world">
        <h2 id="world">world</h2>
      </Link>
    </>
  )
}
